### PR TITLE
[pth] Have license file as %license. JB#55991

### PR DESCRIPTION
**Pull request by pvuorela**
Clean up spec too, removed .yaml and the fedora part of the history.

@Tomin1 @mlehtima

### CODE REVIEW

**Review by Tomin1 — APPROVED** [review]

**Review by Tomin1 — COMMENTED** [review]
Oh, wait! Version number must be updated to a new number in changes and spec, right? (Or alternatively there is a little bit more to these dumb packages than what I know...)

**Comment by pvuorela** [comment]
> Oh, wait! Version number must be updated to a new number in changes and spec, right? (Or alternatively there is a little bit more to these dumb packages than what I know...)

Quite many earlier versions were just "2.7.0" and was about to find out what happens if i just continue that :)

**Comment by Tomin1** [comment]
> > Oh, wait! Version number must be updated to a new number in changes and spec, right? (Or alternatively there is a little bit more to these dumb packages than what I know...)
> 
> Quite many earlier versions were just "2.7.0" and was about to find out what happens if i just continue that :)

Yeah. There are no tags here either.

**Comment by pvuorela** [comment]
Yea, tags don't matter on dumb packages.

**Comment by Tomin1** [comment]
I'm guessing that the last change is so old that CI didn't care or something and now it must be updated. Feel free to merge and then update the version as needed.

**Comment by pvuorela** [comment]
Almost curious enough to test but maybe I'll just fix the versions already as now there are only two remaining.

**Pull request merged**
